---
- hosts: all
  roles:

  - role: alfred
  - role: cask_package
    package_name: dropbox
  - role: cask_package
    package_name: iterm2

  # osx config
  - role: homedir
  - role: dock
    apps:
    - ~/Applications/iTerm.app
    folders:
    - path: ~/
    - path: ~/src/github.com
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-anonymous-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-dejavu
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-dejavu-sans-mono-for-powerline
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-fontawesome
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-inconsolata-dz
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-inconsolata-dz-for-powerline
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-la-belle-aurore
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-symbola
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-terminus

  # languages
  - role: rbenv
  - role: cask_package
    package_name: java

  # nodejs modules
  - role: npm_package
    package_name: bower
  - role: npm_package
    package_name: browserify
  - role: npm_package
    package_name: coffee-script
  - role: npm_package
    package_name: firebase-tools
  - role: npm_package
    package_name: grunt-cli
  - role: npm_package
    package_name: gulp
  - role: npm_package
    package_name: meteorite
  - role: npm_package
    package_name: node-debug
  - role: npm_package
    package_name: nodemon
  - role: npm_package
    package_name: react-tools
  - role: npm_package
    package_name: tern
  - role: npm_package
    package_name: yo

  # ruby gems
  - role: gem_package
    package_name: bundler
  - role: gem_package
    package_name: compass
  - role: gem_package
    package_name: jekyll

